
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> e265cb2ffae2e704c773085e759914aa535aef5b
name: Test(Debug)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Hello World
      run: echo "Hello, World! Hello, World! Hello, World! Hello, World! Hello, World! Hello, World! Hello, World!"
<<<<<<< HEAD
>>>>>>> e265cb2 (merge)
=======
>>>>>>> e265cb2ffae2e704c773085e759914aa535aef5b
